"use client";

import { useState } from "react";
import AuditUpload from "./AuditUpload";
import AuditQuestionnaire from "./AuditQuestionnaire";
import AuditReportView from "./AuditReport";
import { ProjectJson, validateProjectJson, AuditResults } from "@/data/schema";

export default function AuditLanding() {
    const [projectJson, setProjectJson] = useState<ProjectJson | null>(null);
    const [auditResults, setAuditResults] = useState<AuditResults | null>(null);

    const handleUpload = (json: any) => {
        if (validateProjectJson(json)) {
            setProjectJson(json);
        } else {
            alert("Invalid Project JSON file. Please upload a file generated by the Plan Project module.");
        }
    };

    const handleFinishAudit = (results: AuditResults) => {
        setAuditResults(results);
        const updatedProject = { ...projectJson!, auditResults: results };
        setProjectJson(updatedProject);
    };

    const handleReset = () => {
        if (confirm("Are you sure you want to start over? Any unsaved audit progress will be lost.")) {
            setProjectJson(null);
            setAuditResults(null);
        }
    };

    return (
        <div className="max-w-5xl mx-auto py-10 px-4 sm:px-6 lg:px-8">
            <div className="mb-8 border-b border-gray-200 pb-5 flex justify-between items-center">
                <div>
                    <h1 className="text-3xl font-bold text-brand-navy mb-1">Project Audit</h1>
                    {projectJson && (
                        <p className="text-sm text-gray-600">
                            Auditing <span className="font-semibold">{projectJson.projectMeta.projectTitle}</span>
                        </p>
                    )}
                </div>

                {projectJson && (
                    <button
                        onClick={handleReset}
                        className="text-sm font-medium text-gray-500 hover:text-red-600 border border-gray-300 rounded px-3 py-1 hover:border-red-600 transition-colors"
                    >
                        Start Over
                    </button>
                )}
            </div>

            {!projectJson && <AuditUpload onUpload={handleUpload} />}

            {projectJson && !auditResults && (
                <AuditQuestionnaire projectJson={projectJson} onFinish={handleFinishAudit} />
            )}

            {projectJson && auditResults && (
                <AuditReportView projectJson={projectJson} />
            )}
        </div>
    );
}
